my_data =
{
    {type = "ammo", name = "firearm-magazine", ib_data = {ib_let_badge ="FR"} },
    {type = "ammo", name = "piercing-rounds-magazine", ib_data = {ib_let_badge ="PR"} },
    {type = "ammo", name = "pm-high-density-magazine", ib_data = {ib_let_badge ="HDR", ib_img_corner = "top-left"} },
    {type = "ammo", name = "pm-geneva's-neglection-magazine", ib_data = {ib_let_badge ="GNR", ib_img_corner = "top-left"} },
    {type = "ammo", name = "uranium-rounds-magazine", ib_data = {ib_let_badge = "UR"} },
    {type = "ammo", name = "shotgun-shell", ib_data = {ib_let_badge ="BS"} },
    {type = "ammo", name = "piercing-shotgun-shell", ib_data = {ib_let_badge ="PS"} },
    {type = "ammo", name = "pm-high-density-shotgun-shell", ib_data = {ib_let_badge ="HDS", ib_img_corner = "top-left"} },
    {type = "ammo", name = "pm-geneva's-neglection-shotgun-shell", ib_data = {ib_let_badge ="GNS", ib_img_corner = "top-left"} },
    {type = "ammo", name = "pm-shotgun-slug", ib_data = {ib_let_badge ="SS"} },
    {type = "ammo", name = "pm-heavy-piercing-shotgun-slug", ib_data = {ib_let_badge ="PSS", ib_img_corner = "top-left" } },
    {type = "ammo", name = "pm-high-density-shotgun-slug", ib_data = {ib_let_badge ="HSS", ib_img_corner = "top-left"} },
    {type = "ammo", name = "pm-geneva's-neglection-shotgun-slug", ib_data = {ib_let_badge ="GSS", ib_img_corner = "top-left"} },
    
    {type = "module", name = "speed-module", ib_data = {ib_let_badge ="S1"} },
    {type = "module", name = "speed-module-2", ib_data = {ib_let_badge ="S2"} },
    {type = "module", name = "speed-module-3", ib_data = {ib_let_badge ="S3"} },
    {type = "module", name = "pm-speed-module-4", ib_data = {ib_let_badge ="S4"} },
    {type = "module", name = "effectivity-module", ib_data = {ib_let_badge ="E1"} },
    {type = "module", name = "effectivity-module-2", ib_data = {ib_let_badge ="E2"} },
    {type = "module", name = "effectivity-module-3", ib_data = {ib_let_badge ="E3"} },
    {type = "module", name = "pm-effectivity-module-4", ib_data = {ib_let_badge ="E4"} },
    {type = "module", name = "productivity-module", ib_data = {ib_let_badge ="P1"} },
    {type = "module", name = "productivity-module-2", ib_data = {ib_let_badge ="P2"} },
    {type = "module", name = "productivity-module-3", ib_data = {ib_let_badge ="P3"} },
    {type = "module", name = "pm-productivity-module-4", ib_data = {ib_let_badge ="P4"} },

    {type = "item", name = "iron-plate", ib_data = {ib_let_badge ="Fe"} },
    {type = "item", name = "copper-plate", ib_data = {ib_let_badge ="Cu"} },
    {type = "item", name = "pm-nickel-plate", ib_data = {ib_let_badge ="Ni"} },
    {type = "item", name = "pm-zinc-plate", ib_data = {ib_let_badge ="Zn"} },
    {type = "item", name = "pm-manganese-plate", ib_data = {ib_let_badge ="Mn"} },
    {type = "item", name = "pm-gold-plate", ib_data = {ib_let_badge ="Au"} },
    {type = "item", name = "pm-silver-plate", ib_data = {ib_let_badge ="Ag"} },
    {type = "item", name = "pm-titanium-plate", ib_data = {ib_let_badge ="Ti"} },
    {type = "item", name = "pm-tungsten-plate", ib_data = {ib_let_badge ="W"} },
    {type = "item", name = "pm-palladium-plate", ib_data = {ib_let_badge ="Pd"} },
    {type = "item", name = "pm-platinum-plate", ib_data = {ib_let_badge ="Pt"} },
    {type = "item", name = "pm-cobalt-plate", ib_data = {ib_let_badge ="Co"} },
    {type = "item", name = "pm-cadnium-plate", ib_data = {ib_let_badge ="Cd"} },
    {type = "item", name = "pm-aluminium-plate", ib_data = {ib_let_badge ="Al"} },
    {type = "item", name = "pm-tin-plate", ib_data = {ib_let_badge ="Sn"} },
    {type = "item", name = "pm-lead-plate", ib_data = {ib_let_badge ="Pb"} },
    {type = "item", name = "pm-indium-plate", ib_data = {ib_let_badge ="In"} },
    {type = "item", name = "pm-thallium-plate", ib_data = {ib_let_badge ="Tl"} },
    {type = "item", name = "pm-thallium-plate", ib_data = {ib_let_badge ="Te"} },
    {type = "item", name = "pm-bismuth-ore", ib_data = {ib_let_badge ="Bi"} },
    {type = "item", name = "pm-vanadium-ore", ib_data = {ib_let_badge ="V"} },
    {type = "item", name = "pm-chrominum-ore", ib_data = {ib_let_badge ="Cr"} },
    {type = "item", name = "pm-lithium-ore", ib_data = {ib_let_badge ="Li"} },
    {type = "item", name = "pm-lithium-chloride", ib_data = {ib_let_badge ="LiC"} },
    {type = "item", name = "pm-lithium-bromide", ib_data = {ib_let_badge ="LiB"} },
}

for _,i in ipairs(my_data) do
    Build_badge(data.raw[i.type][i.name], i.ib_data)
end
