if not mods["icon-badges"]then return end
my_data =
{
    {type = "ammo", name = "firearm-magazine", ib_data = {ib_let_badge ="FR"}},
    {type = "ammo", name = "piercing-rounds-magazine", ib_data = {ib_let_badge ="PR"}},
    {type = "ammo", name = "pm-high-density-magazine", ib_data = {ib_let_badge ="HDR", ib_img_corner = "left-top"}},
    {type = "ammo", name = "pm-genevas-neglection-magazine", ib_data = {ib_let_badge ="GNR", ib_img_corner = "left-top"}},
    {type = "ammo", name = "uranium-rounds-magazine", ib_data = {ib_let_badge = "UR"}},
    {type = "ammo", name = "shotgun-shell", ib_data = {ib_let_badge ="BS"}},
    {type = "ammo", name = "piercing-shotgun-shell", ib_data = {ib_let_badge ="PS"}},
    {type = "ammo", name = "pm-high-density-shotgun-shell", ib_data = {ib_let_badge ="HDS", ib_img_corner = "left-top"}},
    {type = "ammo", name = "pm-genevas-neglection-shotgun-shell", ib_data = {ib_let_badge ="GNS", ib_img_corner = "left-top"}},
    {type = "ammo", name = "pm-shotgun-slug", ib_data = {ib_let_badge ="SS"}},
    {type = "ammo", name = "pm-heavy-piercing-shotgun-slug", ib_data = {ib_let_badge ="PSS", ib_img_corner = "left-top"}},
    {type = "ammo", name = "pm-high-density-shotgun-slug", ib_data = {ib_let_badge ="HSS", ib_img_corner = "left-top"}},
    {type = "ammo", name = "pm-genevas-neglection-shotgun-slug", ib_data = {ib_let_badge ="GSS", ib_img_corner = "left-top"}},
    
    {type = "module", name = "speed-module", ib_data = {ib_let_badge ="S1"}},
    {type = "module", name = "speed-module-2", ib_data = {ib_let_badge ="S2"}},
    {type = "module", name = "speed-module-3", ib_data = {ib_let_badge ="S3"}},
    {type = "module", name = "pm-speed-module-4", ib_data = {ib_let_badge ="S4"}},
    {type = "module", name = "pm-speed-module-5", ib_data = {ib_let_badge ="S5"}},
    {type = "module", name = "pm-speed-module-6", ib_data = {ib_let_badge ="S6"}},
    {type = "module", name = "efficiency-module", ib_data = {ib_let_badge ="E1"}},
    {type = "module", name = "efficiency-module-2", ib_data = {ib_let_badge ="E2"}},
    {type = "module", name = "efficiency-module-3", ib_data = {ib_let_badge ="E3"}},
    {type = "module", name = "pm-efficiency-module-4", ib_data = {ib_let_badge ="E4"}},
    {type = "module", name = "pm-efficiency-module-5", ib_data = {ib_let_badge ="E5"}},
    {type = "module", name = "pm-efficiency-module-6", ib_data = {ib_let_badge ="E6"}},
    {type = "module", name = "productivity-module", ib_data = {ib_let_badge ="P1"}},
    {type = "module", name = "productivity-module-2", ib_data = {ib_let_badge ="P2"}},
    {type = "module", name = "productivity-module-3", ib_data = {ib_let_badge ="P3"}},
    {type = "module", name = "pm-productivity-module-4", ib_data = {ib_let_badge ="P4"}},
    {type = "module", name = "pm-productivity-module-5", ib_data = {ib_let_badge ="P5"}},
    {type = "module", name = "pm-productivity-module-6", ib_data = {ib_let_badge ="P6"}},

    {type = "item", name = "iron-plate", ib_data = {ib_let_badge ="Fe"}},
    {type = "item", name = "copper-plate", ib_data = {ib_let_badge ="Cu"}},
    {type = "item", name = "pm-nickel-plate", ib_data = {ib_let_badge ="Ni"}},
    {type = "item", name = "pm-zinc-plate", ib_data = {ib_let_badge ="Zn"}},
    {type = "item", name = "pm-manganese-plate", ib_data = {ib_let_badge ="Mn"}},
    {type = "item", name = "pm-gold-plate", ib_data = {ib_let_badge ="Au"}},
    {type = "item", name = "pm-silver-plate", ib_data = {ib_let_badge ="Ag"}},
    {type = "item", name = "pm-titanium-plate", ib_data = {ib_let_badge ="Ti"}},
    {type = "item", name = "pm-tungsten-plate", ib_data = {ib_let_badge ="W"}},
    {type = "item", name = "pm-palladium-plate", ib_data = {ib_let_badge ="Pd"}},
    {type = "item", name = "pm-platinum-plate", ib_data = {ib_let_badge ="Pt"}},
    {type = "item", name = "pm-cobalt-plate", ib_data = {ib_let_badge ="Co"}},
    {type = "item", name = "pm-cadnium-plate", ib_data = {ib_let_badge ="Cd"}},
    {type = "item", name = "pm-aluminium-plate", ib_data = {ib_let_badge ="Al"}},
    {type = "item", name = "pm-tin-plate", ib_data = {ib_let_badge ="Sn"}},
    {type = "item", name = "pm-lead-plate", ib_data = {ib_let_badge ="Pb"}},
    {type = "item", name = "pm-indium-plate", ib_data = {ib_let_badge ="In"}},
    {type = "item", name = "pm-thallium-plate", ib_data = {ib_let_badge ="Tl"}},
    {type = "item", name = "pm-tellurium-plate", ib_data = {ib_let_badge ="Te"}},
    {type = "item", name = "pm-iridium-plate", ib_data = {ib_let_badge ="Ir"}},
    {type = "item", name = "pm-ruthenium-plate", ib_data = {ib_let_badge ="Ru"}},
    {type = "item", name = "pm-rhenium-plate", ib_data = {ib_let_badge ="Re"}},
    {type = "item", name = "pm-rhodium-plate", ib_data = {ib_let_badge ="Rh"}},
    {type = "item", name = "pm-tantalum-plate", ib_data = {ib_let_badge ="Ta"}},
    {type = "item", name = "pm-niobium-plate", ib_data = {ib_let_badge ="Nb"}},
    {type = "item", name = "pm-selenium-plate", ib_data = {ib_let_badge ="Se"}},
    {type = "item", name = "pm-beryllium-plate", ib_data = {ib_let_badge ="Be"}},
    {type = "item", name = "pm-magnesium-plate", ib_data = {ib_let_badge ="Mg"}},
    {type = "item", name = "pm-cerium-plate", ib_data = {ib_let_badge ="Ce"}},
    {type = "item", name = "pm-neodymium-plate", ib_data = {ib_let_badge ="Nd"}},
    {type = "item", name = "pm-dysprosium-plate", ib_data = {ib_let_badge ="Ds"}},
    {type = "item", name = "pm-holmium-plate", ib_data = {ib_let_badge ="Ho"}},
    {type = "item", name = "pm-erbium-plate", ib_data = {ib_let_badge ="Er"}},
    {type = "item", name = "pm-ytterbium-plate", ib_data = {ib_let_badge ="Yb"}},
    {type = "item", name = "steel-plate", ib_data = {ib_let_badge ="ST"}},
    {type = "item", name = "pm-stainless-steel-alloy", ib_data = {ib_let_badge ="SST"}},
    {type = "item", name = "pm-brass-plate", ib_data = {ib_let_badge ="BS"}},
    {type = "item", name = "pm-solder-plate", ib_data = {ib_let_badge ="SR"}},
    {type = "item", name = "pm-kasethal-plate", ib_data = {ib_let_badge ="KS"}},
    {type = "item", name = "pm-inconel-625-plate", ib_data = {ib_let_badge ="IN6"}},
    {type = "item", name = "pm-uhrlumin-plate", ib_data = {ib_let_badge ="UH"}},
    {type = "item", name = "iron-ore", ib_data = {ib_let_badge ="Fe", ib_let_invert = true}},
    {type = "item", name = "copper-ore", ib_data = {ib_let_badge ="Cu", ib_let_invert = true}},
    {type = "item", name = "pm-nickel-ore", ib_data = {ib_let_badge ="Ni", ib_let_invert = true}},
    {type = "item", name = "pm-zinc-ore", ib_data = {ib_let_badge ="Zn", ib_let_invert = true}},
    {type = "item", name = "pm-manganese-ore", ib_data = {ib_let_badge ="Mn", ib_let_invert = true}},
    {type = "item", name = "pm-gold-ore", ib_data = {ib_let_badge ="Au", ib_let_invert = true}},
    {type = "item", name = "pm-silver-ore", ib_data = {ib_let_badge ="Ag", ib_let_invert = true}},
    {type = "item", name = "pm-titanium-ore", ib_data = {ib_let_badge ="Ti", ib_let_invert = true}},
    {type = "item", name = "pm-tungsten-ore", ib_data = {ib_let_badge ="W", ib_let_invert = true}},
    {type = "item", name = "pm-palladium-ore", ib_data = {ib_let_badge ="Pd", ib_let_invert = true}},
    {type = "item", name = "pm-platinum-ore", ib_data = {ib_let_badge ="Pt", ib_let_invert = true}},
    {type = "item", name = "pm-cobalt-ore", ib_data = {ib_let_badge ="Co", ib_let_invert = true}},
    {type = "item", name = "pm-cadnium-ore", ib_data = {ib_let_badge ="Cd", ib_let_invert = true}},
    {type = "item", name = "pm-aluminium-ore", ib_data = {ib_let_badge ="Al", ib_let_invert = true}},
    {type = "item", name = "pm-tin-ore", ib_data = {ib_let_badge ="Sn", ib_let_invert = true}},
    {type = "item", name = "pm-lead-ore", ib_data = {ib_let_badge ="Pb", ib_let_invert = true}},
    {type = "item", name = "pm-indium-ore", ib_data = {ib_let_badge ="In", ib_let_invert = true}},
    {type = "item", name = "pm-thallium-ore", ib_data = {ib_let_badge ="Tl", ib_let_invert = true}},
    {type = "item", name = "pm-tellurium-ore", ib_data = {ib_let_badge ="Te", ib_let_invert = true}},
    {type = "item", name = "pm-iridium-ore", ib_data = {ib_let_badge ="Ir", ib_let_invert = true}},
    {type = "item", name = "pm-ruthenium-ore", ib_data = {ib_let_badge ="Ru", ib_let_invert = true}},
    {type = "item", name = "pm-rheniumoree", ib_data = {ib_let_badge ="Re", ib_let_invert = true}},
    {type = "item", name = "pm-rhodium-ore", ib_data = {ib_let_badge ="Rh", ib_let_invert = true}},
    {type = "item", name = "pm-tantalum-ore", ib_data = {ib_let_badge ="Ta", ib_let_invert = true}},
    {type = "item", name = "pm-niobium-ore", ib_data = {ib_let_badge ="Nb", ib_let_invert = true}},
    {type = "item", name = "pm-selenium-ore", ib_data = {ib_let_badge ="Se", ib_let_invert = true}},
    {type = "item", name = "pm-beryllium-ore", ib_data = {ib_let_badge ="Be", ib_let_invert = true}},
    {type = "item", name = "pm-magnesium-ore", ib_data = {ib_let_badge ="Mg", ib_let_invert = true}},
    {type = "item", name = "pm-cerium", ib_data = {ib_let_badge ="Ce", ib_let_invert = true}},
    {type = "item", name = "pm-neodymium", ib_data = {ib_let_badge ="Nd", ib_let_invert = true}},
    {type = "item", name = "pm-dysprosium", ib_data = {ib_let_badge ="Ds", ib_let_invert = true}},
    {type = "item", name = "pm-holmium", ib_data = {ib_let_badge ="Ho", ib_let_invert = true}},
    {type = "item", name = "pm-erbium", ib_data = {ib_let_badge ="Er", ib_let_invert = true}},
    {type = "item", name = "pm-ytterbium", ib_data = {ib_let_badge ="Yb", ib_let_invert = true}},
    {type = "item", name = "pm-bismuth-ore", ib_data = {ib_let_badge ="Bi"}},
    {type = "item", name = "pm-vanadium-ore", ib_data = {ib_let_badge ="V"}},
    {type = "item", name = "pm-chromium-ore", ib_data = {ib_let_badge ="Cr"}},
    {type = "item", name = "pm-lithium-ore", ib_data = {ib_let_badge ="Li"}},
    {type = "item", name = "pm-lithium-chloride", ib_data = {ib_let_badge ="LiC"}},
    {type = "item", name = "pm-lithium-bromide", ib_data = {ib_let_badge ="LiB"}},
    {type = "item", name = "pm-francium-209", ib_data = {ib_let_badge ="209"}},
    {type = "item", name = "pm-francium-210", ib_data = {ib_let_badge ="210"}},
    {type = "item", name = "pm-francium-211", ib_data = {ib_let_badge ="211"}},
    {type = "item", name = "pm-neodymium-146", ib_data = {ib_let_badge ="146"}},
    {type = "item", name = "pm-neodymium-147", ib_data = {ib_let_badge ="147"}},
    {type = "item", name = "pm-trace-astatine-209", ib_data = {ib_let_badge ="209"}},
    {type = "item", name = "pm-trace-astatine-210", ib_data = {ib_let_badge ="210"}},
    {type = "item", name = "pm-trace-astatine-211", ib_data = {ib_let_badge ="211"}},

    {type = "item", name = "pm-solid-lubricant", ib_data = {ib_let_badge = "SL"}},
    {type = "item", name = "pm-HMX", ib_data = {ib_let_badge = "HMX"}},
    {type = "item", name = "pm-liquid-rocket-fuel-tank", ib_data = {ib_let_badge = "LRF"}},
    {type = "item", name = "pm-liquid-rocket-oxidiser-tank", ib_data = {ib_let_badge = "LRO"}},
    {type = "item", name = "low-density-structure", ib_data = {ib_let_badge = "LDS"}},
    {type = "item", name = "pm-high-density-structure", ib_data = {ib_let_badge = "HDS"}},
    {type = "item", name = "copper-cable", ib_data = {ib_let_badge = "CuC"}},
    {type = "item", name = "pm-gold-wire", ib_data = {ib_let_badge = "AuC"}},
    {type = "item", name = "pm-indium-wire", ib_data = {ib_let_badge = "InC"}},
    {type = "item", name = "pm-sterling-silver-wire", ib_data = {ib_let_badge = "AgC"}},
    {type = "item", name = "pm-polyethylene-plastic", ib_data = {ib_let_badge = "PE"}},
    {type = "item", name = "pm-polymethyl-methacrylate", ib_data = {ib_let_badge = "PMA"}},
    {type = "item", name = "pm-polytetrafluoroethylene-plastic", ib_data = {ib_let_badge = "PTF"}},
    {type = "item", name = "pm-mylar", ib_data = {ib_let_badge = "MYl"}},
    {type = "item", name = "pm-module-speed-light", ib_data = {ib_let_badge = "SL"}},
    {type = "item", name = "pm-module-efficiency-light", ib_data = {ib_let_badge = "EL"}},
    {type = "item", name = "pm-module-productivity-light", ib_data = {ib_let_badge = "PL"}},
    {type = "item", name = "pm-module-quality-light", ib_data = {ib_let_badge = "QL"}},
    {type = "item", name = "pm-advanced-speed-module-light", ib_data = {ib_let_badge = "ASL"}},
    {type = "item", name = "pm-advanced-efficiency-module-light", ib_data = {ib_let_badge = "AEL"}},
    {type = "item", name = "pm-advanced-productivity-module-light", ib_data = {ib_let_badge = "APL"}},
    {type = "item", name = "pm-advanced-quality-module-light", ib_data = {ib_let_badge = "AQL"}},

    {type = "item", name = "battery-equipment", ib_data = {ib_let_badge ="VB"}},
    {type = "item", name = "battery-mk2-equipment", ib_data = {ib_let_badge ="VB2", ib_img_corner = "left-top"}},
    {type = "item", name = "pm-lithium-sulfur-battery-equipment", ib_data = {ib_let_badge ="LB"}},
    {type = "item", name = "pm-lithium-sulfur-battery-mk2-equipment", ib_data = {ib_let_badge ="LB2", ib_img_corner = "left-top"}},
    {type = "item", name = "solar-panel-equipment", ib_data = {ib_let_badge ="SE"}},
    {type = "item", name = "pm-solar-panel-equipment-2", ib_data = {ib_let_badge ="SE2", ib_img_corner = "left-top"}},

    {type = "item", name = "solar-panel", ib_data = {ib_let_badge ="SP"}},
    {type = "item", name = "pm-solar-panel-2", ib_data = {ib_let_badge ="SP2"}},
    {type = "item", name = "pm-solar-panel-2", ib_data = {ib_let_badge ="SP3"}},
    {type = "item", name = "chemical-plant", ib_data = {ib_let_badge ="CP"}},
    {type = "item", name = "pm-chemical-plant-2", ib_data = {ib_let_badge ="CP2",  ib_img_corner = "left-top"}},
    {type = "item", name = "pm-washing-plant-1", ib_data = {ib_let_badge ="WP"}},
    {type = "item", name = "pm-washing-plant-2", ib_data = {ib_let_badge ="WP2",  ib_img_corner = "left-top"}},
    {type = "item", name = "pm-crusher-1", ib_data = {ib_let_badge ="CR"}},
    {type = "item", name = "pm-crusher-2", ib_data = {ib_let_badge ="CR2",  ib_img_corner = "left-top"}},
    {type = "item", name = "transport-belt", ib_data = {ib_let_badge ="B1"}},
    {type = "item", name = "underground-belt", ib_data = {ib_let_badge ="U1"}},
    {type = "item", name = "splitter", ib_data = {ib_let_badge ="S1"}},
    {type = "item", name = "fast-transport-belt", ib_data = {ib_let_badge ="B2"}},
    {type = "item", name = "fast-underground-belt", ib_data = {ib_let_badge ="U2"}},
    {type = "item", name = "fast-splitter", ib_data = {ib_let_badge ="S2"}},
    {type = "item", name = "pm-advanced-transport-belt", ib_data = {ib_let_badge ="B3"}},
    {type = "item", name = "pm-advanced-underground-belt", ib_data = {ib_let_badge ="U3"}},
    {type = "item", name = "pm-advanced-splitter", ib_data = {ib_let_badge ="S3"}},
    {type = "item", name = "express-transport-belt", ib_data = {ib_let_badge ="B4"}},
    {type = "item", name = "express-underground-belt", ib_data = {ib_let_badge ="U4"}},
    {type = "item", name = "express-splitter", ib_data = {ib_let_badge ="S4"}},
    {type = "item", name = "pm-high-density-transport-belt", ib_data = {ib_let_badge ="B5"}},
    {type = "item", name = "pm-high-density-underground-belt", ib_data = {ib_let_badge ="U5"}},
    {type = "item", name = "pm-high-density-splitter", ib_data = {ib_let_badge ="S5"}},

    {type = "item", name = "electronic-circuit", ib_data = {ib_let_badge ="GC"}},
    {type = "item", name = "pm-electronic-breadboard", ib_data = {ib_let_badge ="GB"}},
    {type = "item", name = "pm-electronic-integrated-circuits", ib_data = {ib_let_badge ="IC"}},
    {type = "item", name = "pm-fluid-circuit", ib_data = {ib_let_badge ="OC"}},
    {type = "item", name = "pm-fluid-breadboard", ib_data = {ib_let_badge ="OB"}},
    {type = "item", name = "pm-fluid-integrated-circuits", ib_data = {ib_let_badge ="OIC", ib_img_corner = "left-top"}},
    {type = "item", name = "advanced-circuit", ib_data = {ib_let_badge ="RC"}},
    {type = "item", name = "pm-advanced-circuit-breadboard", ib_data = {ib_let_badge ="RB"}},
    {type = "item", name = "pm-advanced-integrated-circuits", ib_data = {ib_let_badge ="RIC", ib_img_corner = "left-top"}},
    {type = "item", name = "processing-unit", ib_data = {ib_let_badge ="BC"}},
    {type = "item", name = "pm-processing-breadboard", ib_data = {ib_let_badge ="BB"}},
    {type = "item", name = "pm-processing-integrated-circuits", ib_data = {ib_let_badge ="BIC", ib_img_corner = "left-top"}},
    {type = "item", name = "pm-circuit-mold", ib_data = {ib_let_badge ="BRM", ib_img_corner = "left-top"}},
    {type = "item", name = "pm-electronic-breadboard-mold", ib_data = {ib_let_badge ="GM"}},
    {type = "item", name = "pm-fluid-breadboard-mold", ib_data = {ib_let_badge ="OM"}},
    {type = "item", name = "pm-advanced-breadboard-mold", ib_data = {ib_let_badge ="RM"}},
    {type = "item", name = "pm-processing-breadboard-mold", ib_data = {ib_let_badge ="BM"}},
    {type = "item", name = "pm-integrated-circuit-mold", ib_data = {ib_let_badge ="ICM", ib_img_corner = "left-top"}},
    {type = "item", name = "pm-electronic-integrated-circuit-mold", ib_data = {ib_let_badge ="GIM",  ib_img_corner = "left-top"}},
    {type = "item", name = "pm-fluid-integrated-circuit-mold", ib_data = {ib_let_badge ="OIM",  ib_img_corner = "left-top"}},
    {type = "item", name = "pm-advanced-integrated-circuit-mold", ib_data = {ib_let_badge ="RIM",  ib_img_corner = "left-top"}},
    {type = "item", name = "pm-processing-integrated-circuit-mold", ib_data = {ib_let_badge ="BIM",  ib_img_corner = "left-top"}},
    {type = "item", name = "pm-advanced-processing-unit", ib_data = {ib_let_badge ="PC"}},
    {type = "item", name = "pm-space-processing-unit", ib_data = {ib_let_badge ="GC"}},

    {type = "item", name = "pm-vanadium-oxide-catalyst", ib_data = {ib_let_badge ="VC"}},
    {type = "item", name = "pm-palladium-catalyst", ib_data = {ib_let_badge ="PC"}},
    {type = "item", name = "pm-yttrium-catalyst", ib_data = {ib_let_badge ="YC"}},
    {type = "item", name = "pm-cobalt-catalyst", ib_data = {ib_let_badge ="CC"}},
    {type = "item", name = "pm-copper-zinc-aluminium-catalyst", ib_data = {ib_let_badge = "CZC"}},
    {type = "item", name = "pm-nickel-tungsten-catalyst", ib_data = {ib_let_badge = "NTC"}},
    {type = "item", name = "pm-rhenium-platinum-catalyst", ib_data = {ib_let_badge = "RPC"}},
    {type = "item", name = "pm-cobalt-manganese-bromide-catalyst", ib_data = {ib_let_badge = "CMC"}},

    {type = "fluid", name = "pm-liquid-mercury", ib_data = {ib_let_badge ="Hg"}},
    {type = "fluid", name = "pm-mercury-vapour", ib_data = {ib_let_badge ="VHg"}},
    {type = "fluid", name = "pm-oxygen-gas", ib_data = {ib_let_badge ="O"}},
    {type = "fluid", name = "pm-nitrogen-gas", ib_data = {ib_let_badge ="N"}},
    {type = "fluid", name = "pm-chlorine", ib_data = {ib_let_badge ="Cl"}},
    {type = "fluid", name = "pm-hydrochloric-acid", ib_data = {ib_let_badge ="HCl"}},
    {type = "fluid", name = "pm-trace-gas", ib_data = {ib_let_badge ="TG"}},
    {type = "fluid", name = "pm-refinery-gases", ib_data = {ib_let_badge ="RG"}},
    {type = "fluid", name = "pm-hydrogen-flouride", ib_data = {ib_let_badge ="HF"}},
    {type = "fluid", name = "pm-hydroflouric-acid", ib_data = {ib_let_badge ="HF", ib_let_invert = true}},
    {type = "fluid", name = "pm-bromine", ib_data = {ib_let_badge ="Br"}},
    {type = "fluid", name = "pm-boron", ib_data = {ib_let_badge ="B"}},
    {type = "fluid", name = "pm-hydrogen-bromide", ib_data = {ib_let_badge ="HBr"}},
    {type = "fluid", name = "pm-hydrogen-gas", ib_data = {ib_let_badge ="H"}},
    {type = "fluid", name = "pm-helium-gas", ib_data = {ib_let_badge ="He"}},
    {type = "fluid", name = "pm-argon-gas", ib_data = {ib_let_badge ="Ar"}},
    {type = "fluid", name = "pm-butane-gas", ib_data = {ib_let_badge ="Ba"}},
    {type = "fluid", name = "pm-butene-gas", ib_data = {ib_let_badge ="Be"}},
    {type = "fluid", name = "pm-molten-iron", ib_data = {ib_let_badge ="MFe"}},
    {type = "fluid", name = "pm-molten-copper", ib_data = {ib_let_badge ="MCu"}},
    {type = "fluid", name = "pm-molten-nickel", ib_data = {ib_let_badge ="MNi"}},
    {type = "fluid", name = "pm-molten-manganese", ib_data = {ib_let_badge ="MMn"}},
    {type = "fluid", name = "pm-molten-zinc", ib_data = {ib_let_badge ="MZn"}},
    {type = "fluid", name = "pm-molten-gold", ib_data = {ib_let_badge ="MAu"}},
    {type = "fluid", name = "pm-molten-silver", ib_data = {ib_let_badge ="MAg"}},
    {type = "fluid", name = "pm-molten-titanium", ib_data = {ib_let_badge ="MTi"}},
    {type = "fluid", name = "pm-molten-tungsten", ib_data = {ib_let_badge ="MW"}},
    {type = "fluid", name = "pm-molten-cobalt", ib_data = {ib_let_badge ="MCo"}},
    {type = "fluid", name = "pm-molten-cadnium", ib_data = {ib_let_badge ="MCd"}},
    {type = "fluid", name = "pm-molten-palladium", ib_data = {ib_let_badge ="MPd"}},
    {type = "fluid", name = "pm-molten-platinum", ib_data = {ib_let_badge ="MPt"}},
    {type = "fluid", name = "pm-molten-aluminium", ib_data = {ib_let_badge ="MAl"}},
    {type = "fluid", name = "pm-molten-tin", ib_data = {ib_let_badge ="MSn"}},
    {type = "fluid", name = "pm-molten-lead", ib_data = {ib_let_badge ="MPb"}},
    {type = "fluid", name = "pm-molten-indium", ib_data = {ib_let_badge ="MIn"}},
    {type = "fluid", name = "pm-molten-thallium", ib_data = {ib_let_badge ="MTl"}},
    {type = "fluid", name = "pm-oil-residuals", ib_data = {ib_let_badge ="RO"}},
    {type = "fluid", name = "pm-fuel-oils", ib_data = {ib_let_badge ="FO"}},
    {type = "fluid", name = "pm-lubricating-oils", ib_data = {ib_let_badge ="LO"}},
    {type = "fluid", name = "pm-diesel", ib_data = {ib_let_badge ="DI"}},
    {type = "fluid", name = "pm-petrol", ib_data = {ib_let_badge ="PT"}},
    {type = "fluid", name = "pm-kerosene", ib_data = {ib_let_badge ="KE"}},
    {type = "fluid", name = "pm-naptha", ib_data = {ib_let_badge ="NP"}},
    {type = "fluid", name = "pm-liquid-gallium", ib_data = {ib_let_badge ="Ga"}},
    {type = "fluid", name = "pm-molten-nickel", ib_data = {ib_let_badge ="MNi"}},
    {type = "fluid", name = "pm-xenon-gas", ib_data = {ib_let_badge ="Xe"}},
    {type = "fluid", name = "pm-neon-gas", ib_data = {ib_let_badge ="Ne"}},
    {type = "fluid", name = "pm-krypton-gas", ib_data = {ib_let_badge ="Kr"}},
    {type = "fluid", name = "pm-radon-gas", ib_data = {ib_let_badge ="Rn"}},
    {type = "fluid", name = "pm-RP-1", ib_data = {ib_let_badge = "RP1"}},

    {type = "tool", name = "automation-science-pack", ib_data = {ib_let_badge ="TM"}},
    {type = "tool", name = "logistic-science-pack", ib_data = {ib_let_badge ="ATM"}},
    {type = "tool", name = "pm-advanced-advanced-transition-metal-science-pack", ib_data = {ib_let_badge ="AAT"}},
    {type = "tool", name = "pm-post-transition-metal-science-pack", ib_data = {ib_let_badge ="PTM"}},
    {type = "tool", name = "chemical-science-pack", ib_data = {ib_let_badge ="RNM"}},
    {type = "tool", name = "pm-metalloid-science-pack", ib_data = {ib_let_badge ="MT"}},
    {type = "tool", name = "pm-alkali-metal-science-pack", ib_data = {ib_let_badge ="AM"}},
    {type = "tool", name = "pm-advanced-advanced-advanced-transition-metal-science-pack", ib_data = {ib_let_badge = "AAA"}},
    {type = "tool", name = "pm-alkaline-earth-metal-science-pack", ib_data = {ib_let_badge = "AEM"}},
    {type = "tool", name = "pm-noble-gas-science-pack", ib_data = {ib_let_badge = "NB"}},
    {type = "tool", name = "pm-lanthanide-science-pack", ib_data = {ib_let_badge = "LA"}}
}

for _,i in ipairs(my_data) do
    local item = data.raw[i.type][i.name]
    if item then
        Build_badge(item, i.ib_data)
    end
end
Ib_global.badge_vanilla = false
