my_data =
{
    {type = "ammo", name = "firearm-magazine", ib_data = {ib_let_badge ="FR"} },
    {type = "ammo", name = "piercing-rounds-magazine", ib_data = {ib_let_badge ="PR"} },
    {type = "ammo", name = "pm-high-density-magazine", ib_data = {ib_let_badge ="HDR", ib_img_corner = "top-left"} },
    {type = "ammo", name = "pm-geneva's-neglection-magazine", ib_data = {ib_let_badge ="GNR", ib_img_corner = "top-left"} },
    {type = "ammo", name = "uranium-rounds-magazine", ib_data = {ib_let_badge = "UR"} },
    {type = "ammo", name = "shotgun-shell", ib_data = {ib_let_badge ="BS"} },
    {type = "ammo", name = "piercing-shotgun-shell", ib_data = {ib_let_badge ="PS"} },
    {type = "ammo", name = "pm-high-density-shotgun-shell", ib_data = {ib_let_badge ="HDS", ib_img_corner = "top-left"} },
    {type = "ammo", name = "pm-geneva's-neglection-shotgun-shell", ib_data = {ib_let_badge ="GNS", ib_img_corner = "top-left"} },
    {type = "ammo", name = "pm-shotgun-slug", ib_data = {ib_let_badge ="SS"} },
    {type = "ammo", name = "pm-heavy-piercing-shotgun-slug", ib_data = {ib_let_badge ="PSS", ib_img_corner = "top-left" } },
    {type = "ammo", name = "pm-high-density-shotgun-slug", ib_data = {ib_let_badge ="HSS", ib_img_corner = "top-left"} },
    {type = "ammo", name = "pm-geneva's-neglection-shotgun-slug", ib_data = {ib_let_badge ="GSS", ib_img_corner = "top-left"} },
    

    {type = "module", name = "speed-module", ib_data = {ib_let_badge ="S1"} },
    {type = "module", name = "speed-module-2", ib_data = {ib_let_badge ="S2"} },
    {type = "module", name = "speed-module-3", ib_data = {ib_let_badge ="S3"} },
    {type = "module", name = "pm-speed-module-4", ib_data = {ib_let_badge ="S4"} },
    {type = "module", name = "effectivity-module", ib_data = {ib_let_badge ="E1"} },
    {type = "module", name = "effectivity-module-2", ib_data = {ib_let_badge ="E2"} },
    {type = "module", name = "effectivity-module-3", ib_data = {ib_let_badge ="E3"} },
    {type = "module", name = "pm-effectivity-module-4", ib_data = {ib_let_badge ="E4"} },
    {type = "module", name = "productivity-module", ib_data = {ib_let_badge ="P1"} },
    {type = "module", name = "productivity-module-2", ib_data = {ib_let_badge ="P2"} },
    {type = "module", name = "productivity-module-3", ib_data = {ib_let_badge ="P3"} },
    {type = "module", name = "pm-productivity-module-4", ib_data = {ib_let_badge ="P4"} },


    {type = "item", name = "iron-plate", ib_data = {ib_let_badge ="Fe"} },
    {type = "item", name = "copper-plate", ib_data = {ib_let_badge ="Cu"} },
    {type = "item", name = "pm-nickel-plate", ib_data = {ib_let_badge ="Ni"} },
    {type = "item", name = "pm-zinc-plate", ib_data = {ib_let_badge ="Zn"} },
    {type = "item", name = "pm-manganese-plate", ib_data = {ib_let_badge ="Mn"} },
    {type = "item", name = "pm-gold-plate", ib_data = {ib_let_badge ="Au"} },
    {type = "item", name = "pm-silver-plate", ib_data = {ib_let_badge ="Ag"} },
    {type = "item", name = "pm-titanium-plate", ib_data = {ib_let_badge ="Ti"} },
    {type = "item", name = "pm-tungsten-plate", ib_data = {ib_let_badge ="W"} },
    {type = "item", name = "pm-palladium-plate", ib_data = {ib_let_badge ="Pd"} },
    {type = "item", name = "pm-platinum-plate", ib_data = {ib_let_badge ="Pt"} },
    {type = "item", name = "pm-cobalt-plate", ib_data = {ib_let_badge ="Co"} },
    {type = "item", name = "pm-cadnium-plate", ib_data = {ib_let_badge ="Cd"} },
    {type = "item", name = "pm-aluminium-plate", ib_data = {ib_let_badge ="Al"} },
    {type = "item", name = "pm-tin-plate", ib_data = {ib_let_badge ="Sn"} },
    {type = "item", name = "pm-lead-plate", ib_data = {ib_let_badge ="Pb"} },
    {type = "item", name = "pm-indium-plate", ib_data = {ib_let_badge ="In"} },
    {type = "item", name = "pm-thallium-plate", ib_data = {ib_let_badge ="Tl"} },
    {type = "item", name = "pm-thallium-plate", ib_data = {ib_let_badge ="Te"} },
    {type = "item", name = "steel-plate", ib_data = {ib_let_badge ="ST"} },
    {type = "item", name = "pm-stainless-steel-alloy", ib_data = {ib_let_badge ="SST"} },
    {type = "item", name = "pm-brass-plate", ib_data = {ib_let_badge ="BS"} },
    {type = "item", name = "pm-solder-plate", ib_data = {ib_let_badge ="SR"} },
    {type = "item", name = "pm-kasethal-plate", ib_data = {ib_let_badge ="KS"} },
    {type = "item", name = "iron-ore", ib_data = {ib_let_badge ="Fe", ib_let_invert = true} },
    {type = "item", name = "copper-ore", ib_data = {ib_let_badge ="Cu", ib_let_invert = true} },
    {type = "item", name = "pm-nickel-ore", ib_data = {ib_let_badge ="Ni", ib_let_invert = true} },
    {type = "item", name = "pm-zinc-ore", ib_data = {ib_let_badge ="Zn", ib_let_invert = true} },
    {type = "item", name = "pm-manganese-ore", ib_data = {ib_let_badge ="Mn", ib_let_invert = true} },
    {type = "item", name = "pm-gold-ore", ib_data = {ib_let_badge ="Au", ib_let_invert = true} },
    {type = "item", name = "pm-silver-ore", ib_data = {ib_let_badge ="Ag", ib_let_invert = true} },
    {type = "item", name = "pm-titanium-ore", ib_data = {ib_let_badge ="Ti", ib_let_invert = true} },
    {type = "item", name = "pm-tungsten-ore", ib_data = {ib_let_badge ="W", ib_let_invert = true} },
    {type = "item", name = "pm-palladium-ore", ib_data = {ib_let_badge ="Pd", ib_let_invert = true} },
    {type = "item", name = "pm-platinum-ore", ib_data = {ib_let_badge ="Pt", ib_let_invert = true} },
    {type = "item", name = "pm-cobalt-ore", ib_data = {ib_let_badge ="Co", ib_let_invert = true} },
    {type = "item", name = "pm-cadnium-ore", ib_data = {ib_let_badge ="Cd", ib_let_invert = true} },
    {type = "item", name = "pm-aluminium-ore", ib_data = {ib_let_badge ="Al", ib_let_invert = true} },
    {type = "item", name = "pm-tin-ore", ib_data = {ib_let_badge ="Sn", ib_let_invert = true} },
    {type = "item", name = "pm-lead-ore", ib_data = {ib_let_badge ="Pb", ib_let_invert = true} },
    {type = "item", name = "pm-indium-ore", ib_data = {ib_let_badge ="In", ib_let_invert = true} },
    {type = "item", name = "pm-thallium-ore", ib_data = {ib_let_badge ="Tl", ib_let_invert = true} },
    {type = "item", name = "pm-thallium-ore", ib_data = {ib_let_badge ="Te", ib_let_invert = true} },
    {type = "item", name = "pm-bismuth-ore", ib_data = {ib_let_badge ="Bi"} },
    {type = "item", name = "pm-vanadium-ore", ib_data = {ib_let_badge ="V"} },
    {type = "item", name = "pm-chrominum-ore", ib_data = {ib_let_badge ="Cr"} },
    {type = "item", name = "pm-lithium-ore", ib_data = {ib_let_badge ="Li"} },
    {type = "item", name = "pm-lithium-chloride", ib_data = {ib_let_badge ="LiC"} },
    {type = "item", name = "pm-lithium-bromide", ib_data = {ib_let_badge ="LiB"} },
    {type = "item", name = "pm-francium-209", ib_data = {ib_let_badge ="209"} },
    {type = "item", name = "pm-francium-210", ib_data = {ib_let_badge ="210"} },
    {type = "item", name = "pm-francium-211", ib_data = {ib_let_badge ="211"} },

    {type = "item", name = "battery-equipment", ib_data = {ib_let_badge ="VB"} },
    {type = "item", name = "battery-mk2-equipment", ib_data = {ib_let_badge ="VB2",  ib_img_corner = "top-left"} },
    {type = "item", name = "pm-lithium-sulfur-battery-equipment", ib_data = {ib_let_badge ="LB"} },
    {type = "item", name = "pm-lithium-sulfur-battery-mk2-equipment", ib_data = {ib_let_badge ="LB2",  ib_img_corner = "top-left"} },
    {type = "item", name = "solar-panel-equipment", ib_data = {ib_let_badge ="SE"} },
    {type = "item", name = "pm-solar-panel-equipment-2", ib_data = {ib_let_badge ="SE2",  ib_img_corner = "top-left"} },

    {type = "item", name = "solar-panel", ib_data = {ib_let_badge ="SP"} },
    {type = "item", name = "pm-solar-panel-2", ib_data = {ib_let_badge ="SP2",  ib_img_corner = "top-left"} },
    {type = "item", name = "chemical-plant", ib_data = {ib_let_badge ="CP"} },
    {type = "item", name = "pm-chemical-plant-2", ib_data = {ib_let_badge ="CP2",  ib_img_corner = "top-left"} },
    {type = "item", name = "pm-washing-plant-1", ib_data = {ib_let_badge ="WP"} },
    {type = "item", name = "pm-washing-plant-2", ib_data = {ib_let_badge ="WP2",  ib_img_corner = "top-left"} },
    {type = "item", name = "pm-crusher-1", ib_data = {ib_let_badge ="CR"} },
    {type = "item", name = "pm-crusher-2", ib_data = {ib_let_badge ="CR2",  ib_img_corner = "top-left"} },


    {type = "fluid", name = "pm-francium", ib_data = {ib_let_badge ="Fr"} },
    {type = "fluid", name = "pm-liquid-mercury", ib_data = {ib_let_badge ="Hg"} },
    {type = "fluid", name = "pm-mercury-vapour", ib_data = {ib_let_badge ="VHg"} },
    {type = "fluid", name = "pm-oxygen-gas", ib_data = {ib_let_badge ="O"} },
    {type = "fluid", name = "pm-nitrogen-gas", ib_data = {ib_let_badge ="N"} },
    {type = "fluid", name = "pm-chlorine", ib_data = {ib_let_badge ="Cl"} },
    {type = "fluid", name = "pm-hydrochloric-acid", ib_data = {ib_let_badge ="HCl"} },
    {type = "fluid", name = "pm-trace-gas", ib_data = {ib_let_badge ="TG"} },
    {type = "fluid", name = "pm-refinery-gases", ib_data = {ib_let_badge ="RG"} },
    {type = "fluid", name = "pm-hydrogen-flouride", ib_data = {ib_let_badge ="HF"} },
    {type = "fluid", name = "pm-hydroflouric-acid", ib_data = {ib_let_badge ="HF", ib_let_invert = true} },
    {type = "fluid", name = "pm-bromine", ib_data = {ib_let_badge ="Br"} },
    {type = "fluid", name = "pm-boron", ib_data = {ib_let_badge ="B"} },
    {type = "fluid", name = "pm-hydrogen-bromide", ib_data = {ib_let_badge ="HBr"} },
    {type = "fluid", name = "pm-hydrogen-gas", ib_data = {ib_let_badge ="H"} },
    {type = "fluid", name = "pm-helium-gas", ib_data = {ib_let_badge ="He"} },
    {type = "fluid", name = "pm-argon-gas", ib_data = {ib_let_badge ="Ar"} },
    {type = "fluid", name = "pm-butane-gas", ib_data = {ib_let_badge ="Ba"} },
    {type = "fluid", name = "pm-butene-gas", ib_data = {ib_let_badge ="Be"} },
    {type = "fluid", name = "pm-molten-iron", ib_data = {ib_let_badge ="MFe"} },
    {type = "fluid", name = "pm-molten-copper", ib_data = {ib_let_badge ="MCu"} },
    {type = "fluid", name = "pm-molten-nickel", ib_data = {ib_let_badge ="MNi"} },
    {type = "fluid", name = "pm-molten-manganese", ib_data = {ib_let_badge ="MMn"} },
    {type = "fluid", name = "pm-molten-zinc", ib_data = {ib_let_badge ="MZn"} },
    {type = "fluid", name = "pm-molten-gold", ib_data = {ib_let_badge ="MAu"} },
    {type = "fluid", name = "pm-molten-silver", ib_data = {ib_let_badge ="MAg"} },
    {type = "fluid", name = "pm-molten-titanium", ib_data = {ib_let_badge ="MTi"} },
    {type = "fluid", name = "pm-molten-tungsten", ib_data = {ib_let_badge ="MW"} },
    {type = "fluid", name = "pm-molten-cobalt", ib_data = {ib_let_badge ="MCo"} },
    {type = "fluid", name = "pm-molten-cadnium", ib_data = {ib_let_badge ="MCd"} },
    {type = "fluid", name = "pm-molten-palladium", ib_data = {ib_let_badge ="MPd"} },
    {type = "fluid", name = "pm-molten-platinum", ib_data = {ib_let_badge ="MPt"} },
    {type = "fluid", name = "pm-molten-aluminium", ib_data = {ib_let_badge ="MAl"} },
    {type = "fluid", name = "pm-molten-tin", ib_data = {ib_let_badge ="MSn"} },
    {type = "fluid", name = "pm-molten-lead", ib_data = {ib_let_badge ="MPb"} },
    {type = "fluid", name = "pm-molten-indium", ib_data = {ib_let_badge ="MIn"} },
    {type = "fluid", name = "pm-molten-thallium", ib_data = {ib_let_badge ="MTl"} },
    {type = "fluid", name = "pm-oil-residuals", ib_data = {ib_let_badge ="RO"} },
    {type = "fluid", name = "pm-fuel-oils", ib_data = {ib_let_badge ="FO"} },
    {type = "fluid", name = "pm-lubricating-oils", ib_data = {ib_let_badge ="LO"} },
    {type = "fluid", name = "pm-diesel", ib_data = {ib_let_badge ="DI"} },
    {type = "fluid", name = "pm-petrol", ib_data = {ib_let_badge ="PT"} },
    {type = "fluid", name = "pm-kerosene", ib_data = {ib_let_badge ="KE"} },
    {type = "fluid", name = "pm-naptha", ib_data = {ib_let_badge ="NP"} },
    {type = "fluid", name = "pm-caesium", ib_data = {ib_let_badge ="Ce"} },
    {type = "fluid", name = "pm-liquid-gallium", ib_data = {ib_let_badge ="Ga"} },
    {type = "fluid", name = "pm-molten-nickel", ib_data = {ib_let_badge ="MNi"} },


    {type = "tool", name = "automation-science-pack", ib_data = {ib_let_badge ="TM"} },
    {type = "tool", name = "logistic-science-pack", ib_data = {ib_let_badge ="ATM"} },
    {type = "tool", name = "pm-advanced-advanced-transition-metal-science-pack", ib_data = {ib_let_badge ="AAT"} },
    {type = "tool", name = "pm-post-transition-metal-science-pack", ib_data = {ib_let_badge ="PTM"} },
    {type = "tool", name = "chemical-science-pack", ib_data = {ib_let_badge ="RNM"} },
    {type = "tool", name = "pm-metalloid-science-pack", ib_data = {ib_let_badge ="MT"} },
    {type = "tool", name = "pm-alkali-metal-science-pack", ib_data = {ib_let_badge ="AM"} },
}

for _,i in ipairs(my_data) do
    Build_badge(data.raw[i.type][i.name], i.ib_data)
end
