--for.. fluids

data:extend({

  {
    type = "fluid",
    name = "pm-hydrochloric-acid",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/hydrochloric-acid.png",
    subgroup = "pm-acids",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0, g = 0.8, b = 0.34},
    flow_color = {r = 0, g = 0.8, b = 0.34}
  },
  {
    type = "fluid",
    name = "pm-chlorine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/chlorine.png",
    subgroup = "pm-acids",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0, g = 1, b = 0},
    flow_color = {r = 0, g = 1, b = 0}
  },
  {
    type = "fluid",
    name = "pm-acidic-water",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/acidic-water.png",
    subgroup = "pm-acids",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.16, g = 0.89, b = 0.69},
    flow_color = {r = 0.16, g = 0.69, b = 0.29},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-liquid-mercury",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/liquid-mercury.png",
    subgroup = "pm-mercury-tm",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.6, b = 0.6},
    flow_color = {r = 0.6, g = 0.6, b = 0.6}
  },
  {
    type = "fluid",
    name = "pm-seawater",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/seawater.png",
    default_temperature = 15,
    heat_capacity = "1kJ",
    base_color = {r = 0.3, g = 0.69, b = 0.98},
    flow_color = {r = 0.3, g = 0.69, b = 0.98}
  },
  {
    type = "fluid",
    name = "pm-resin",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/resin.png",
    subgroup = "pm-resin",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.99, g = 0.98, b = 0.94},
    flow_color = {r = 0.99, g = 0.98, b = 0.94}
  },
  {
    type = "fluid",
    name = "pm-rubber-resin",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/rubber-resin.png",
    subgroup = "pm-resin",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.89, g = 0.78, b = 0.14},
    flow_color = {r = 0.89, g = 0.78, b = 0.14}
  },
  {
    type = "fluid",
    name = "pm-pheonlic-resin",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/pheonlic-resin.png",
    subgroup = "pm-resin",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.14, g = 0.95, b = 0.29},
    flow_color = {r = 0.14, g = 0.95, b = 0.29}
  },

  {
    type = "fluid",
    name = "pm-oil-residuals",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/oil-residuals.png",
    default_temperature = 15,
    base_color = {r = 0, g = 0, b = 0},
    flow_color = {r = 0, g = 0, b = 0}
  },
  {
    type = "fluid",
    name = "pm-fuel-oils",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/fuel-oils.png",
    default_temperature = 15,
    base_color = {r = 0.61, g = 0.4, b = 0},
    flow_color = {r = 0.61, g = 0.4, b = 0}
  },
  {
    type = "fluid",
    name = "pm-lubricating-oils",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/lubricating-oils.png",
    default_temperature = 15,
    base_color = {r = 0, g = 0.4, b = 0},
    flow_color = {r = 0, g = 0.4, b = 0}
  },
  {
    type = "fluid",
    name = "pm-diesel",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/diesel.png",
    default_temperature = 15,
    base_color = {r = 0.333, g = 0.333, b = 0.332},
    flow_color = {r = 0.333, g = 0.333, b = 0.332}
  },
  {
    type = "fluid",
    name = "pm-kerosene",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/kerosene.png",
    default_temperature = 15,
    base_color = {r = 0.666, g = 0.666, b = 0.666},
    flow_color = {r = 0.666, g = 0.666, b = 0.666}
  },
  {
    type = "fluid",
    name = "pm-naptha",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/naptha.png",
    default_temperature = 15,
    base_color = {r = 0, g = 0, b = 0.4},
    flow_color = {r = 0, g = 0, b = 0.4}
  },
  {
    type = "fluid",
    name = "pm-petrol",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/petrol.png",
    default_temperature = 15,
    base_color = {r = 0.5, g = 0, b = 0},
    flow_color = {r = 0.5, g = 0, b = 0}
  },
  {
    type = "fluid",
    name = "pm-refinery-gases",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/refinery-gases.png",
    default_temperature = 15,
    base_color = {r = 0.77, g = 0.639, b = 0},
    flow_color = {r = 0.77, g = 0.639, b = 0}
  },
  {
    type = "fluid",
    name = "pm-butane-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/butane-gas.png",
    default_temperature = 15,
    base_color = {r = 1, g = 1, b = 1 },
    flow_color = {r = 1, g = 1, b = 1 }
  },
  {
    type = "fluid",
    name = "pm-butene-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/butene-gas.png",
    default_temperature = 15,
    base_color = {r = 0.7, g = 0.7, b = 0.7},
    flow_color = {r = 0.7, g = 0.7, b = 0.7}
  },
  {
    type = "fluid",
    name = "pm-ethylene-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/ethylene-gas.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.671, b = 0.8},
    flow_color = {r = 0.8, g = 0.671, b = 0.8},
  },
  {
    type = "fluid",
    name = "pm-legendary-diesel",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/legendary-diesel.png",
    default_temperature = 15,
    base_color = {r = 0.666, g = 0.666, b = 0.332},
    flow_color = {r = 0.666, g = 0.666, b = 0.332},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-common-diesel",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/common-diesel.png",
    default_temperature = 15,
    base_color = {r = 0.555, g = 0.555, b = 0.555},
    flow_color = {r = 0.555, g = 0.555, b = 0.555},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-heavy-lubricant",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/heavy-lubricant.png",
    fuel_value = "1MJ",
    default_temperature = 15,
    base_color = {r = 0, g = 0.3, b = 0},
    flow_color = {r = 0, g = 0.3, b = 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-sulfur-dioxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/sulfur-dioxide.png",
    subgroup = "pm-sulfur-rnm",
    order = "ba",
    default_temperature = 15,
    base_color = {r = 1, g = 1, b = 0},
    flow_color = {r = 1, g = 1, b = 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-atmosphere",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/atmosphere.png",
    subgroup = "pm-atmosphere-rnm",
    order = "a",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.21, g = 0.21, b = 0.42},
    flow_color = {r = 0.21, g = 0.21, b = 0.42},
  },
  {
    type = "fluid",
    name = "pm-vanadium-oxide-positive-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/vanadium-oxide-positive-solution.png",
    subgroup = "pm-batteries",
    order = "j",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.18, g = 0.21, b = 0.22},
    flow_color = {r = 0.18, g = 0.21, b = 0.22},
  },
  {
    type = "fluid",
    name = "pm-vanadium-oxide-negative-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/vanadium-oxide-negative-solution.png",
    subgroup = "pm-batteries",
    order = "k",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.18, g = 0.21, b = 0.22},
    flow_color = {r = 0.18, g = 0.21, b = 0.22},
  },
  {
    type = "fluid",
    name = "pm-mercury-vapour",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/mercury-vapour.png",
    subgroup = "pm-mercury-tm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-oxygen-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/oxygen-gas.png",
    subgroup = "pm-oxygen-rnm",
    order = "a",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 1, g = 0, b = 0},
    flow_color = {r = 1, g = 0, b = 0}
  },
  {
    type = "fluid",
    name = "pm-nitrogen-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/nitrogen-gas.png",
    subgroup = "pm-nitrogen-rnm",
    order = "a",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0, g = 0, b = 1 },
    flow_color = {r = 0, g = 0, b = 1 }
  },
  {
    type = "fluid",
    name = "pm-carbon-dioxide-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/carbon-dioxide.png",
    subgroup = "pm-carbon-rnm",
    order = "b",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0, g = 0, b = 0},
    flow_color = {r = 0, g = 0, b = 0}
  },
  {
    type = "fluid",
    name = "pm-trace-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/trace-gas.png",
    subgroup = "pm-trace-gas-rnm",
    order = "a",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.18, g = 0.21, b = 0.22},
    flow_color = {r = 0.18, g = 0.21, b = 0.22},
  },
  {
    type = "fluid",
    name = "pm-molten-iron",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-iron.png",
    subgroup = "pm-iron-tm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-copper",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-copper.png",
    subgroup = "pm-copper-tm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.89, g = 0.6, b = 0},
    flow_color = {r = 0.89, g = 0.6, b = 0},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-nickel",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-nickel.png",
    subgroup = "pm-nickel-tm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.86, b = 0.88},
    flow_color = {r = 0.6, g = 0.86, b = 0.88},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-zinc",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-zinc.png",
    subgroup = "pm-zinc-tm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.3, b = 0.2},
    flow_color = {r = 0.6, g = 0.3, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-manganese",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-manganese.png",
    subgroup = "pm-manganese-tm",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.8},
    flow_color = {r = 0.3, g = 0.3, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-gold",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-gold.png",
    subgroup = "pm-gold-tm",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.6, b = 0},
    flow_color = {r = 0.6, g = 0.6, b = 0},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-silver",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-silver.png",
    subgroup = "pm-silver-tm",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.92, g = 0.92, b = 0.92},
    flow_color = {r = 0.92, g = 0.92, b = 0.92},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-tin",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-tin.png",
    subgroup = "pm-tin-ptm",
    order = "f",
    default_temperature = 15,
    base_color = {r = 0.67, g = 0.67, b = 1 },
    flow_color = {r = 0.67, g = 0.67, b = 1 },
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-titanium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-titanium.png",
    subgroup = "pm-titanium-tm",
    order = "f",
    default_temperature = 15,
    base_color = {r = 0.67, g = 0.67, b = 0.67},
    flow_color = {r = 0.67, g = 0.67, b = 0.67},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-tungsten",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-tungsten.png",
    subgroup = "pm-tungsten-tm",
    order = "f",
    default_temperature = 15,
    base_color = {r = 0.82, g = 0.67, b = 0.67},
    flow_color = {r = 0.82, g = 0.67, b = 0.67},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-cadnium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-cadmium.png",
    subgroup = "pm-cadmium-tm",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.91, g = 0.87, b = 0.67},
    flow_color = {r = 0.91, g = 0.87, b = 0.67},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-aluminium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-aluminium.png",
    subgroup = "pm-aluminium-ptm",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.91, g = 0.87, b = 0.67},
    flow_color = {r = 0.91, g = 0.87, b = 0.67},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-platinum",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-platinum.png",
    subgroup = "pm-platinum-tm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.49, g = 0.49, b = 0.2},
    flow_color = {r = 0.49, g = 0.49, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-indium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-indium.png",
    subgroup = "pm-indium-ptm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.38, g = 0.49, b = 0.74},
    flow_color = {r = 0.38, g = 0.49, b = 0.74},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-thallium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-thallium.png",
    subgroup = "pm-thallium-ptm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.38, g = 0.39, b = 0.38},
    flow_color = {r = 0.38, g = 0.39, b = 0.38},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-cobalt",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-cobalt.png",
    subgroup = "pm-cobalt-tm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.08, g = 0.09, b = 1 },
    flow_color = {r = 0.08, g = 0.09, b = 1 },
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-palladium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-palladium.png",
    subgroup = "pm-platinum-tm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.89, g = 0.62, b = 0.44},
    flow_color = {r = 0.89, g = 0.62, b = 0.44},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-beryllium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-beryllium.png",
    subgroup = "pm-beryllium-aem",
    order = "h",
    default_temperature = 15,
    base_color = {r = 0.75, g = 0.62, b = 0.34},
    flow_color = {r = 0.75, g = 0.62, b = 0.34},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-glass",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-glass.png",
    subgroup = "pm-glassing",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-borosilicate-glass",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/liquid-borosillicate-glass.png",
    subgroup = "pm-glassing",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.6},
    flow_color = {r = 0.8, g = 0.8, b = 0.6},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-solder",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/liquid-solder.png",
    subgroup = "pm-alloys",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.62, g = 0.49, b = 0.37},
    flow_color = {r = 0.62, g = 0.49, b = 0.37},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-steel",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/liquid-steel.png",
    subgroup = "pm-alloys",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.6, b = 0.6},
    flow_color = {r = 0.6, g = 0.6, b = 0.6},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-stainless-steel",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/liquid-stainless-steel.png",
    subgroup = "pm-alloys",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.49, g = 0.49, b = 0.8},
    flow_color = {r = 0.49, g = 0.49, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-brass",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/liquid-brass.png",
    subgroup = "pm-alloys",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.7, b = 0.6},
    flow_color = {r = 0.8, g = 0.7, b = 0.6},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-kasethal",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/liquid-kasethal.png",
    subgroup = "pm-alloys",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.92, g = 0.94, b = 0.68},
    flow_color = {r = 0.92, g = 0.94, b = 0.68},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-zinc-tailings",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/zinc-tailings.png",
    subgroup = "pm-vanadium-tm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.62, g = 0.49, b = 0.37},
    flow_color = {r = 0.62, g = 0.49, b = 0.37},
  },
  {
    type = "fluid",
    name = "pm-helium-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/helium-gas.png",
    subgroup = "pm-helium-nb",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.7, g = 1, b = 0.7},
    flow_color = {r = 0.7, g = 1, b = 0.7},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-argon-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/argon-gas.png",
    subgroup = "pm-argon-nb",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0, b = 0},
    flow_color = {r = 0.6, g = 0, b = 0},
    auto_barrel = false,
    fuel_value = "0.4MJ"
  },
  {
    type = "fluid",
    name = "pm-water-vapour",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/water-vapour.png",
    subgroup = "fluid",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.8, b = 0.6},
    flow_color = {r = 0.6, g = 0.8, b = 0.6},
  },
  {
    type = "fluid",
    name = "pm-benzene",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/benzene.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8}
  },
  {
    type = "fluid",
    name = "pm-acetone",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/acetone.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8}
  },
  {
    type = "fluid",
    name = "pm-bisphenol-A",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/dont-model-your-molecules-A.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8}
  },
  {
    type = "fluid",
    name = "pm-nickel-tailings",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/nickel-tailings.png",
    subgroup = "pm-cadmium-tm",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.32, g = 0.49, b = 0.87},
    flow_color = {r = 0.32, g = 0.49, b = 0.87},
  },
  {
    type = "fluid",
    name = "pm-chromic-acid",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/chromic-acid.png",
    subgroup = "pm-acids",
    default_temperature = 15,
    base_color = {r = 0.82, g = 0, b = 0.87},
    flow_color = {r = 0.82, g = 0, b = 0.87},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-nickel-froth",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/nickel-froth.png",
    subgroup = "pm-cadmium-tm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.32, g = 0.49, b = 0.87},
    flow_color = {r = 0.32, g = 0.49, b = 0.87},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-cellouse-pulp",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/cellouse-pulp.png",
    default_temperature = 15,
    base_color = {r = 0.32, g = 0.49, b = 0.87},
    flow_color = {r = 0.32, g = 0.49, b = 0.87},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-agar-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/agar-solution.png",
    default_temperature = 15,
    base_color = {r = 0.99, g = 0.98, b = 0.6},
    flow_color = {r = 0.99, g = 0.98, b = 0.6},
    auto_barrel = false,
    fuel_value = "0.8MJ"
  },
  {
    type = "fluid",
    name = "pm-bacteriaed-agar-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/bacteria'ed-agar-solution.png",
    default_temperature = 15,
    base_color = {r = 0.99, g = 0.6, b = 0.98},
    flow_color = {r = 0.99, g = 0.6, b = 0.98},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-ammonia-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/ammonia.png",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.6, b = 1 },
    flow_color = {r = 0.6, g = 0.6, b = 1 },
  },
  {
    type = "fluid",
    name = "pm-gene-base",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/gene-base.png",
    default_temperature = 15,
    base_color = {r = 0.4, g = 0.4, b = 0.6},
    flow_color = {r = 0.4, g = 0.4, b = 0.6},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-trace-acetonitrile",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/trace-acetonitrile.png",
    default_temperature = 15,
    base_color = {r = 0.2, g = 0.2, b = 0.6},
    flow_color = {r = 0.2, g = 0.2, b = 0.6},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-acetonitrile",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/acetonitrile.png",
    default_temperature = 15,
    base_color = {r = 0.2, g = 0.2, b = 0.8},
    flow_color = {r = 0.2, g = 0.2, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-phosphoramidite",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/phosphoramidite.png",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.4, b = 0},
    flow_color = {r = 0.6, g = 0.4, b = 0},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-common-myostatin",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/common-myostatin.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-broken-myostatin",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/broken-myostatin.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-rare-myostatin",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/rare-myostatin.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-legendary-myostatin",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/legendary-myostatin.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-CISD2",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/CISD2.png",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.8, b = 0.8},
    flow_color = {r = 0.8, g = 0.8, b = 0.8},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-phosphoric-acid",
    subgroup = "pm-phosphorus-rnm",
    order = "a",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/phosphoric-acid.png",
    default_temperature = 15,
    base_color = {r = 1, g = 0.6, b = 0.6},
    flow_color = {r = 1, g = 0.6, b = 0.6}
  },
  {
    type = "fluid",
    name = "pm-phosphor-vapour",
    subgroup = "pm-phosphorus-rnm",
    order = "b",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/phosphor-vapour.png",
    default_temperature = 15,
    base_color = {r = 1, g = 0.6, b = 0.6},
    flow_color = {r = 1, g = 0.6, b = 0.6},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-hydrogen-flouride",
    subgroup = "pm-flourine-rnm",
    order = "a",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/hydrogen-flouride.png",
    default_temperature = 15,
    base_color = {r = 0.2, g = 1, b = 1 },
    flow_color = {r = 0.2, g = 1, b = 1 },
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-hydroflouric-acid",
    subgroup = "pm-flourine-rnm",
    order = "b",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/hydroflouric-acid.png",
    default_temperature = 15,
    base_color = {r = 0.2, g = 1, b = 1 },
    flow_color = {r = 0.2, g = 1, b = 1 },
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-plaster-of-nauvis",
    subgroup = "pm-plastic-science-process",
    order = "A",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/plaster-of-nauvis.png",
    default_temperature = 15,
    base_color = {r = 1, g = 0.7, b = 0.7},
    flow_color = {r = 1, g = 0.7, b = 0.7}
  },
  {
    type = "fluid",
    name = "pm-molten-lead",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-lead.png",
    subgroup = "pm-lead-ptm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.278, g = 0.143, b = 0},
    flow_color = {r = 0.278, g = 0.143, b = 0},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-lead-froth",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/lead-froth.png",
    subgroup = "pm-lead-ptm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.478, g = 0.343, b = 0},
    flow_color = {r = 0.478, g = 0.343, b = 0},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-sodium-hydroxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/sodium-hydroxide.png",
    subgroup = "pm-gallium-ptm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 1, g = 0.842, b = 0.862},
    flow_color = {r = 1, g = 0.842, b = 0.862},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-gallium-liqour",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/gallium-liqour.png",
    subgroup = "pm-gallium-ptm",
    order = "b",
    default_temperature = 15,
    base_color = {r = 1, g = 0.842, b = 0.862},
    flow_color = {r = 1, g = 0.842, b = 0.862},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-liquid-gallium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/liquid-gallium.png",
    subgroup = "pm-gallium-ptm",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.6, b = 0.7},
    flow_color = {r = 0.6, g = 0.6, b = 0.7}
  },
  {
    type = "fluid",
    name = "pm-coolant",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/coolant.png",
    subgroup = "pm-bismuth-ptm",
    order = "a",
    default_temperature = 15,
    fuel_value = "1MJ",
    base_color = {r = 0.247, g = 0.82, b = 1 },
    flow_color = {r = 0.247, g = 0.82, b = 1 },
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-ethylene-glycol",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/ethylene-glycol.png",
    subgroup = "pm-bismuth-ptm",
    order = "A",
    default_temperature = 15,
    base_color = {r = 1, g = 0.82, b = 0.82},
    flow_color = {r = 1, g = 0.82, b = 0.82},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-creosote",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/creosote.png",
    default_temperature = 15,
    base_color = {r = 0.4, g = 0.3, b = 0.2},
    flow_color = {r = 0.4, g = 0.3, b = 0.2},
  },
  {
    type = "fluid",
    name = "pm-hydrogen-gas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/hydrogen-gas.png",
    subgroup = "pm-hydrogen-rnm",
    order = "A",
    default_temperature = 15,
    base_color = {r = 1, g = 1, b = 1 },
    flow_color = {r = 1, g = 1, b = 1 },
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-proton-beam",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/proton-beam.png",
    subgroup = "pm-hydrogen-rnm",
    order = "A",
    default_temperature = 15,
    fuel_value = "1MJ",
    base_color = {r = 0.9, g = 0.9, b = 1 },
    flow_color = {r = 0.9, g = 0.9, b = 1 },
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-carbon-monoxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/carbon-monoxide.png",
    subgroup = "pm-carbon-rnm",
    order = "c",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.1, g = 0.1, b = 0.1 },
    flow_color = {r = 0.1, g = 0.1, b = 0.1 }
  },
  {
    type = "fluid",
    name = "pm-methanol",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/methanol.png",
    subgroup = "pm-plastics",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.4, g = 0.1, b = 0.1 },
    flow_color = {r = 0.4, g = 0.1, b = 0.1 }
  },
  {
    type = "fluid",
    name = "pm-methyl-methacrylate",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/methyl-methacrylate.png",
    subgroup = "pm-plastics",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.2, g = 0.1, b = 0.1 },
    flow_color = {r = 0.2, g = 0.1, b = 0.1 }
  },
  {
    type = "fluid",
    name = "pm-ferric-chloride",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/ferric-chloride.png",
    subgroup = "pm-circuits",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.4, g = 0.66, b = 0.4},
    flow_color = {r = 0.4, g = 0.66, b = 0.4}
  },
  {
    type = "fluid",
    name = "pm-copper-froth",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/copper-froth.png",
    subgroup = "pm-cobalt-tm",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.46, g = 0.4, b = 0.26},
    flow_color = {r = 0.46, g = 0.4, b = 0.26}
  },
  {
    type = "fluid",
    name = "pm-copper-tailings",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/copper-tailings.png",
    subgroup = "pm-cobalt-tm",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.56, g = 0.422, b = 0.22},
    flow_color = {r = 0.56, g = 0.422, b = 0.22}
  },
  {
    type = "fluid",
    name = "pm-brine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/brine.png",
    subgroup = "pm-lithium-am",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.16, g = 0.89, b = 0.79},
    flow_color = {r = 0.16, g = 0.69, b = 0.79},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-phosgene",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/phosgene.png",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.8, b = 0.6},
    flow_color = {r = 0.6, g = 0.8, b = 0.6},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-cyanobacteriaed-agar-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/cyanobacteria'ed-agar-solution.png",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.6, b = 0.98},
    flow_color = {r = 0.6, g = 0.6, b = 0.98},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-melatonin",
    icon_size = 128,
    icon = "__periodic-madness__/graphics/icons/fluids/melatonin.png",
    default_temperature = 15,
    base_color = {r = 0.6, g = 0.6, b = 0.8},
    flow_color = {r = 0.6, g = 0.6, b = 0.8},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-ethylene-carbonate",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/ethylene-carbonate.png",
    subgroup = "pm-batteries",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.82, g = 0.42, b = 0.42},
    flow_color = {r = 0.82, g = 0.42, b = 0.42},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-low-brine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/low-brine.png",
    subgroup = "pm-lithium-am",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.16, g = 0.99, b = 0.89},
    flow_color = {r = 0.16, g = 0.99, b = 0.89},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-med-brine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/med-brine.png",
    subgroup = "pm-lithium-am",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.16, g = 0.99, b = 0.99},
    flow_color = {r = 0.16, g = 0.99, b = 0.99},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-high-brine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/high-brine.png",
    subgroup = "pm-lithium-am",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.26, g = 0.99, b = 0.99},
    flow_color = {r = 0.26, g = 0.99, b = 0.99},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-lithium-hydroxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/lithium-hydroxide.png",
    subgroup = "pm-lithium-am",
    order = "x",
    default_temperature = 15,
    base_color = {r = 0.863, g = 0.842, b = 1 },
    flow_color = {r = 0.863, g = 0.842, b = 1 },
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-hydrogen-bromide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/hydrogen-bromide.png",
    subgroup = "pm-bromine-rnm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 1, g = 0.675, b = 0.2},
    flow_color = {r = 1, g = 0.675, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-bromine-ions",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/bromine-ions.png",
    subgroup = "pm-bromine-rnm",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.7, g = 0.64, b = 0},
    flow_color = {r = 0.7, g = 0.64, b = 0},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-trace-bromine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/trace-bromine.png",
    subgroup = "pm-bromine-rnm",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.75, g = 0.68, b = 0.6},
    flow_color = {r = 0.75, g = 0.68, b = 0.6},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-bromine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/bromine.png",
    subgroup = "pm-bromine-rnm",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.67, g = 0.36, b = 0},
    flow_color = {r = 0.67, g = 0.36, b = 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-vinyl-bromide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/vinyl-bromide.png",
    subgroup = "pm-bromine-rnm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.67, g = 0.36, b = 0},
    flow_color = {r = 0.67, g = 0.36, b = 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-methyl-chloride",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/methyl-chloride.png",
    subgroup = "pm-chlorine-rnm",
    order = "za",
    default_temperature = 15,
    base_color = {r = 0.33, g = 0.66, b = 0.32},
    flow_color = {r = 0.33, g = 0.66, b = 0.32},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-carbon-tetrachloride",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/carbon-tetrachloride.png",
    subgroup = "pm-chlorine-rnm",
    order = "x",
    default_temperature = 15,
    base_color = {r = 0.33, g = 0.99, b = 0.32},
    flow_color = {r = 0.33, g = 0.99, b = 0.32},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-chloronated-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/chloronated-solution.png",
    subgroup = "pm-chlorine-rnm",
    order = "y",
    default_temperature = 15,
    base_color = {r = 0.66, g = 0.99, b = 0.66},
    flow_color = {r = 0.66, g = 0.99, b = 0.66},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-tetrafluoroethylene",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/tetrafluoroethylene.png",
    subgroup = "pm-plastics",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.3, g = 0.1, b = 0.2},
    flow_color = {r = 0.3, g = 0.1, b = 0.2}
  },
  {
    type = "fluid",
    name = "pm-chloroform",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/chloroform.png",
    subgroup = "pm-chlorine-rnm",
    order = "z",
    default_temperature = 15,
    base_color = {r = 0.66, g = 0.99, b = 0.66},
    flow_color = {r = 0.66, g = 0.99, b = 0.66},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-sulfur-trioxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/sulfur-trioxide.png",
    default_temperature = 15,
    base_color = {r = 1, g = 0.8, b = 0},
    flow_color = {r = 1, g = 0.8, b = 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-oleum",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/oleum.png",
    default_temperature = 15,
    base_color = {r = 1, g = 1, b = 0},
    flow_color = {r = 1, g = 1, b = 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-vanadate-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/vanadate-solution.png",
    default_temperature = 15,
    base_color = {r = 0.529, g = 0.43, b = 0.35},
    flow_color = {r = 0.529, g = 0.43, b = 0.35},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-acidic-brine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/acidic-brine.png",
    subgroup = "pm-iodine-rnm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.16, g = 0.89, b = 0.69},
    flow_color = {r = 0.16, g = 0.69, b = 0.29},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-iodine-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/iodine-solution.png",
    subgroup = "pm-iodine-rnm",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.67, g = 0, b = 0.67},
    flow_color = {r = 0.67, g = 0, b = 0.67},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-hydrogen-iodide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/hydrogen-iodine.png",
    subgroup = "pm-iodine-rnm",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.96, g = 0.85, b = 1 },
    flow_color = {r = 0.96, g = 0.85, b = 1 },
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-boron",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/boron.png",
    subgroup = "pm-boron-mt",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.67, g = 0.36, b = 0},
    flow_color = {r = 0.67, g = 0.36, b = 0},
  },
  {
    type = "fluid",
    name = "pm-diluted-boric-acid",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/diluted-boric-acid.png",
    subgroup = "pm-boron-mt",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.67, g = 0.36, b = 0},
    flow_color = {r = 0.67, g = 0.36, b = 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-ethylolamine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/ethylene-glycol.png",
    subgroup = "pm-boron-mt",
    order = "a",
    default_temperature = 15,
    base_color = {r = 1, g = 0.82, b = 0.82},
    flow_color = {r = 1, g = 0.82, b = 0.82},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-potassium-salts",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-potassium-salts.png",
    subgroup = "pm-potassium-am",
    order = "x",
    default_temperature = 15,
    base_color = {r = 1, g = 0.52, b = 0.79},
    flow_color = {r = 1, g = 0.52, b = 0.79},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-carbon-trioxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/carbon-trioxide.png",
    subgroup = "pm-carbon-rnm",
    order = "d",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.2, g = 0, b = 0},
    flow_color = {r = 0.2, g = 0, b = 0}
  },
  {
    type = "fluid",
    name = "pm-aqueous-yttrium-fluoride",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/aqueous-yttrium-fluoride.png",
    subgroup = "pm-yttrium-tm",
    order = "e",
    default_temperature = 15,
    base_color = {r = 1, g = 0.52, b = 0.79},
    flow_color = {r = 1, g = 0.52, b = 0.79},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-copper-sludge",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/copper-sludge.png",
    subgroup = "pm-tellurium-mt",
    order = "a",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.56, g = 0.422, b = 0.22},
    flow_color = {r = 0.56, g = 0.422, b = 0.22}
  },
  {
    type = "fluid",
    name = "pm-arsine",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/arsine.png",
    subgroup = "pm-arsenic-mt",
    order = "a",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 1, g = 0.68, b = 0.88},
    flow_color = {r = 1, g = 0.68, b = 0.88}
  },
  {
    type = "fluid",
    name = "pm-crystal-slurry",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/crystal-slurry.png",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.29, g = 0.168, b = 0.458},
    flow_color = {r = 0.29, g = 0.168, b = 0.458}
  },
  {
    type = "fluid",
    name = "pm-hydrogen-peroxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/seawater.png",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.3, g = 0.69, b = 0.98},
    flow_color = {r = 0.3, g = 0.69, b = 0.98}
  },
  {
    type = "fluid",
    name = "pm-silane",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/silane.png",
    subgroup = "pm-silicon-mt",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.968, g = 0.68, b = 1},
    flow_color = {r = 0.968, g = 0.68, b = 1}
  },
  {
    type = "fluid",
    name = "pm-silicon-tetrachloride",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/silicon-tetrachloride.png",
    subgroup = "pm-silicon-mt",
    order = "c",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.968, g = 0.68, b = 1},
    flow_color = {r = 0.968, g = 0.68, b = 1}
  },
  {
    type = "fluid",
    name = "pm-trichlorosilane",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/trichlorosilane.png",
    subgroup = "pm-silicon-mt",
    order = "a",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.968, g = 0.68, b = 1},
    flow_color = {r = 0.968, g = 0.68, b = 1}
  },
  {
    type = "fluid",
    name = "pm-dichlorosilane",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/dichlorosilane.png",
    subgroup = "pm-silicon-mt",
    order = "b",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.968, g = 0.68, b = 1},
    flow_color = {r = 0.968, g = 0.68, b = 1}
  },
  {
    type = "fluid",
    name = "pm-dimethyldichlorosilane",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/dimethyldichlorosilane.png",
    subgroup = "pm-silicon-mt",
    order = "ba",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.968, g = 0.68, b = 1},
    flow_color = {r = 0.968, g = 0.68, b = 1}
  },
  {
    type = "fluid",
    name = "pm-liquid-silicone",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/silicone.png",
    default_temperature = 15,
    subgroup = "pm-silicon-mt",
    order = "x",
    base_color = {r = 1, g = 0.7, b = 0.7},
    flow_color = {r = 1, g = 0.7, b = 0.7}
  },
  {
    type = "fluid",
    name = "pm-concrete-slurry",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/concrete-slurry.png",
    subgroup = "terrain",
    order = "A",
    default_temperature = 15,
    base_color = {r = 0.5, g = 0.5, b = 0.5},
    flow_color = {r = 0.5, g = 0.5, b = 0.5}
  },
  {
    type = "fluid",
    name = "pm-light-coolant",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/coolant.png",
    subgroup = "pm-bismuth-ptm",
    order = "a",
    default_temperature = 15,
    fuel_value = "2MJ",
    base_color = {r = 0.447, g = 0.92, b = 1 },
    flow_color = {r = 0.447, g = 0.92, b = 1 },
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-polydimethylsiloxane",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/dimethyldichlorosilane.png",
    subgroup = "pm-silicon-mt",
    order = "ba",
    default_temperature = 15,
    auto_barrel = false,
    base_color = {r = 0.968, g = 0.68, b = 1},
    flow_color = {r = 0.968, g = 0.68, b = 1}
  },
  {
    type = "fluid",
    name = "pm-calcium-hydroxide-slurry",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/calcium-hydroxide-slurry.png",
    subgroup = "pm-calcium-aem",
    order = "ca",
    default_temperature = 15,
    base_color = {r = 0.75, g = 0.75, b = 0.75},
    flow_color = {r = 0.75, g = 0.75, b = 0.75}
  },
  {
    type = "fluid",
    name = "pm-calcium-sulfate-slurry",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/calcium-sulfate-slurry.png",
    subgroup = "pm-calcium-aem",
    order = "f",
    default_temperature = 15,
    base_color = {r = 0.99, g = 0.85, b = 0.85},
    flow_color = {r = 0.99, g = 0.85, b = 0.85},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-magnesium-hydroxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/magnesium-hydroxide.png",
    subgroup = "pm-magnesium-aem",
    order = "c",
    default_temperature = 15,
    base_color = {r = 1, g = 0.842, b = 0.862},
    flow_color = {r = 1, g = 0.842, b = 0.862},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-high-sulfur-residuals",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/high-sulfur-residuals.png",
    subgroup = "pm-chrominum-tm",
    order = "A",
    default_temperature = 15,
    base_color = {r = 0.4, g = 0.4, b = 0.2},
    flow_color = {r = 0.4, g = 0.4, b = 0.2}
  },
  {
    type = "fluid",
    name = "pm-low-sulfur-residuals",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/low-sulfur-residuals.png",
    subgroup = "pm-vanadium-tm",
    order = "A",
    default_temperature = 15,
    base_color = {r = 0.2, g = 0.2, b = 0.2},
    flow_color = {r = 0.2, g = 0.2, b = 0.2}
  },
  {
    type = "fluid",
    name = "pm-cupric-waste-water",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/cupric-waste-water.png",
    default_temperature = 15,
    base_color = {r = 0.56, g = 0.422, b = 0.22},
    flow_color = {r = 0.56, g = 0.422, b = 0.22}
  },
  {
    type = "fluid",
    name = "pm-ferrous-waste-water",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/ferrous-waste-water.png",
    default_temperature = 15,
    base_color = {r = 0.56, g = 0.422, b = 0.22},
    flow_color = {r = 0.56, g = 0.422, b = 0.22}
  },
  {
    type = "fluid",
    name = "pm-aluminium-hydroxide-slurry",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/aluminium-hydroxide.png",
    subgroup = "pm-aluminium-ptm",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.75, g = 0.75, b = 0.75},
    flow_color = {r = 0.75, g = 0.75, b = 0.75}
  },
  {
    type = "fluid",
    name = "pm-titanium-chloride",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/titanium-tetrachloride.png",
    subgroup = "pm-titanium-tm",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.33, g = 0.66, b = 0.32},
    flow_color = {r = 0.33, g = 0.66, b = 0.32},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-mixed-molten-iron",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/mixed-molten-iron.png",
    subgroup = "pm-advanced-iron-tm",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-ore-slag",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-ore-slag.png",
    subgroup = "pm-advanced-iron-tm",
    order = "c",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-barium-froth",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/placeholder-item.png",
    subgroup = "pm-barium-aem",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
  },
  {
    type = "fluid",
    name = "pm-barium-tailings",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/barium-tailings.png",
    subgroup = "pm-barium-aem",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
  },
  {
    type = "fluid",
    name = "pm-barium-vapour",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/placeholder-item.png",
    subgroup = "pm-barium-aem",
    order = "g",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
  },
  {
    type = "fluid",
    name = "pm-beryllium-hydroxide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/beryllium-hydroxide.png",
    subgroup = "pm-beryllium-aem",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
  },
  {
    type = "fluid",
    name = "pm-ammonium-tetrafluoroberyllate",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/ammonium-tetrafluoroberyllate.png",
    subgroup = "pm-beryllium-aem",
    order = "f",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
  },
  {
    type = "fluid",
    name = "pm-sulfur-dichloride",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/sulfur-dichloride.png",
    subgroup = "pm-radium-aem",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
  },
  {
    type = "fluid",
    name = "pm-strontium-sulfide-solution",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/placeholder-item.png",
    subgroup = "pm-strontium-aem",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
  },
  {
    type = "fluid",
    name = "pm-syngas",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/syngas.png",
    subgroup = "pm-strontium-aem",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.1, b = 0.1},
    flow_color = {r = 0.3, g = 0.1, b = 0.1},
  },
  {
    type = "fluid",
    name = "pm-matte-copper",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/matte-copper.png",
    subgroup = "pm-advanced-copper-tm",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-matte-nickel",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/matte-nickel.png",
    subgroup = "pm-advanced-nickel-tm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-mixed-nickel-concentrate",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/matte-nickel.png",
    subgroup = "pm-advanced-nickel-tm",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-zinc-sulfide-concentrate",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/zinc-sulfide-concentrate.png",
    subgroup = "pm-advanced-zinc-tm",
    order = "b",
    default_temperature = 15,
    base_color = {r = 0.3, g = 0.3, b = 0.2},
    flow_color = {r = 0.3, g = 0.3, b = 0.2},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-zinc-froth",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/nickel-froth.png",
    subgroup = "pm-advanced-zinc-tm",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.32, g = 0.49, b = 0.87},
    flow_color = {r = 0.32, g = 0.49, b = 0.87},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-zinc-vapour",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/vanadate-solution.png",
    subgroup = "pm-advanced-zinc-tm",
    order = "d",
    default_temperature = 15,
    base_color = {r = 0.529, g = 0.43, b = 0.35},
    flow_color = {r = 0.529, g = 0.43, b = 0.35},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "pm-molten-strontium-glass",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-glass.png",
    subgroup = "pm-glassing",
    order = "a",
    default_temperature = 15,
    base_color = {r = 0.8, g = 0.6, b = 0.6},
    flow_color = {r = 0.8, g = 0.6, b = 0.6},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-sulfuric-waste-water",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/sulfuric-waste-water.png",
    default_temperature = 15,
    base_color = {r = 0.56, g = 0.422, b = 0.22},
    flow_color = {r = 0.56, g = 0.422, b = 0.22}
  },
  {
    type = "fluid",
    name = "pm-hydrogen-sulfide",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/hydrogen-sulfide.png",
    default_temperature = 15,
    base_color = {r = 0.56, g = 0.422, b = 0.22},
    flow_color = {r = 0.56, g = 0.422, b = 0.22}
  },
  {
    type = "fluid",
    name = "pm-molten-cadmium-telluride",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-cadmium-telluride.png",
    subgroup = "pm-cadmium-tm",
    order = "f",
    default_temperature = 15,
    base_color = {r = 0.38, g = 0.39, b = 0.38},
    flow_color = {r = 0.38, g = 0.39, b = 0.38},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "pm-molten-magnesium",
    icon_size = 64,
    icon = "__periodic-madness__/graphics/icons/fluids/molten-magnesium.png",
    subgroup = "pm-magnesium-aem",
    order = "e",
    default_temperature = 15,
    base_color = {r = 0.91, g = 0.87, b = 0.67},
    flow_color = {r = 0.91, g = 0.87, b = 0.67},
    auto_barrel = false,
  },

	{
		type = "fluid",
		name = "pm-liquid-heat",
    icons = {
      { -- FIXME: add a better (probably more stylized) icon
        icon = "__core__/graphics/arrows/heat-exchange-indication.png",
        scale = 1,
        icon_size = 48,
        draw_background = false,
      },
      -- HACK: if the hovered icons are too annoying. Maybe make a setting?
      -- util.empty_icon()
    },
		hidden = true,
		auto_barrel = false,
		base_color = {1,0,0},
		flow_color = {1,0,0},
		default_temperature = 15,
		fuel_value = "50kJ",
	},
}--[[@as data.FluidPrototype[] ]])

data.raw["fluid"]["sulfuric-acid"].icon = "__periodic-madness__/graphics/icons/fluids/sulfuric-acid.png"
data.raw["fluid"]["light-oil"].auto_barrel = false
data.raw["fluid"]["petroleum-gas"].auto_barrel = false
data.raw["fluid"]["heavy-oil"].auto_barrel = false

data.raw["fluid"]["water"].fuel_value = "1MJ"